### ISSUE TITLE
mapping grid reference on timed-count entry page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#350]
Hi @DavidRoy 

When setting up a new transect and drawing in the section routes, the map helpfully shows the grid reference of the cursor (box in top right corner).

Would it be possible to include this feature on the map when drawing in a polygon for the timed-count data entry?

Many thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook I've deployed a change to Live to display the OSGB grid reference at the top of the timed count map, in the same way as the Transect route map.

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

Sounds good, but I'm not seeing it?

<img width="666" alt="image" src="https://github.com/user-attachments/assets/7d8c241e-31cb-40de-9bff-3892300a438c">

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : It should only be visible when your mouse is over the map.

**Comment by IanMiddlebrook** [comment]
Thanks @Gary-van-Breda  
I knew that, but was still not seeing it at the time.
It's there now, so I probably just needed to clear my cache.

thanks again, Ian
